#!/usr/bin/env python3
import socketserver

class TracksailTCPHandler(socketserver.BaseRequestHandler):
    def handle(self):
        self.data = self.request.recv(1024).strip()
        print("{} wrote:".format(self.client_address[0]))
        print(self.data)
        self.request.sendall('10')

if __name__ == "__main__":
    HOST, PORT = 'localhost', 5555

    server = socketserver.TCPServer((HOST, PORT), TracksailTCPHandler)
    server.serve_forever()
